version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python main.py
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python test.py
  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - run: echo "deploying to"
    

workflows:
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main    
notifications:
  webhooks:
    - url: https://hooks.slack.com/services/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  



      
